version: "2"
services:
  ddclient:
    image: linuxserver/ddclient # para raspberrypi: lsioarmhf/ddclient
    container_name: ddclient
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - ./config:/config
    restart: unless-stopped
